name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Build the changelog
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3.6.0
      with:
        configuration: ".github/configs/release-changelog-builder-action.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{ github.event.release.tag_name }}
        url: https://github.com/${{ github.repository }}
        manifest: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json
        download: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.zip

    # Create a zip file with all files required by the module to add to the release
    - run: zip -r ./module.zip module.json *.md *.js img/ lang/ packs/ screenshots/ scripts/ styles/ templates/

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        name: ${{ github.event.release.name }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json, ./module.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ steps.build_changelog.outputs.changelog }}

    # Push release to Foundry
    - id: foundryvtt_release
      uses: illandril/FoundryVTT-package-release-action@v1
      with:
        package-release-token: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
        manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/module.json
